CC="gcc -arch i386" \
PLATFORM=osx32 \
LIBNAME=libcairo.dylib \
CFLAGS="-Wno-attributes -DCAIRO_HAS_PTHREAD=1 -DHAVE_INT128_T" \
IMAGE_SURFACE=1 \
PNG_FUNCTIONS=1 \
RECORDING_SURFACE=1 \
SVG_SURFACE=1 \
PS_SURFACE=1 \
PDF_SURFACE=1 \
FT_FONT=1 \
./build.sh
